Final project 6 - выполнено задание
Badgurich/java-kanban pull request #1
Opened 2024-12-02 17:44 UTC by Badgurich

2024-12-03 07:09 UTC, VadimZharkov commented on src/ru/yandex/practicum/taskmanager/interfaces/TaskManager.java
>  		ArrayList<Subtask> getLinkedSubtasks(Epic epic);
Хорошей практикой считается объявлять параметры метода базовым типом (часто это интерфейс).
Например, List<Task> getTaskList(); 
Такой подход добавляет гибкости при необходимости заменить одну реализацию на другую.

2024-12-03 07:14 UTC, VadimZharkov reviewed
Раскладывать типы по их видам (enums, interfaces, tasktypes) смыслат нет. Лучше группировать типы по их смысловой принадлежности, на пример tasks, managers, utils.

2024-12-03 07:16 UTC, VadimZharkov commented on src/ru/yandex/practicum/taskmanager/util/InMemoryHistoryManager.java
Посмотри, что с форматированием файлов. Почему такие огромные отступы.

2024-12-03 07:18 UTC, VadimZharkov commented on src/ru/yandex/practicum/taskmanager/util/InMemoryHistoryManager.java
> +		}
Нужно еще удалить из мапы

2024-12-03 07:19 UTC, VadimZharkov commented on src/ru/yandex/practicum/taskmanager/util/InMemoryHistoryManager.java
> +		public void linkLast(Task task) {
Служебный метод, лучше сделать приватным

2024-12-03 07:19 UTC, VadimZharkov commented on src/ru/yandex/practicum/taskmanager/util/InMemoryHistoryManager.java
> +		public void removeNode(Node<Task> node) {
Служебный метод, лучше сделать приватным

2024-12-03 07:20 UTC, VadimZharkov requested changes
Нужно исправить замечания

2024-12-05 13:55 UTC, badgurich commented on src/ru/yandex/practicum/taskmanager/util/InMemoryHistoryManager.java
Не знаю, везде по авто код стайлу сделано, у меня вроде адекватно все выглядит. Сейчас запушу, один-два лишних пробела удалил

2024-12-05 14:13 UTC, VadimZharkov approved these changes

2024-12-05 14:22 UTC, merged